#!/usr/bin/env Rscript

# Author: Nicole Tignor
# Affiliation: Icahn School of Medicine at Mount Sinai

# Figure 1F source-derived age-segmentation support. This script applies the
# exploratory temporalCPSA contiguous age-segmentation diagnostic to the
# source-derived AD-TMP matrix generated by
# Figure1F_AD_TMP_heatmap_source_derived.R. It does not reproduce the original
# manuscript age-class selection step directly; rather, it provides a
# transparent final-data support analysis showing which age-contiguous
# molecular intervals are favored by the source-derived AD-TMP matrix.

resolve_script_dir <- function(script_name) {
  for (frame in rev(sys.frames())) {
    ofile <- frame$ofile
    if (!is.null(ofile) && basename(ofile) == script_name && file.exists(ofile)) {
      return(dirname(normalizePath(ofile, mustWork = TRUE)))
    }
  }
  script_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(script_arg) > 0) {
    script_path <- gsub("~\\+~", " ", sub("^--file=", "", script_arg[[1]]))
    return(dirname(normalizePath(script_path, mustWork = TRUE)))
  }
  if (file.exists(file.path(getwd(), script_name))) {
    return(normalizePath(getwd(), mustWork = TRUE))
  }
  stop("Cannot determine script directory for `", script_name, "`. Run from the script folder or with Rscript.", call. = FALSE)
}
script_dir <- resolve_script_dir("Figure1F_AD_TMP_age_segmentation_support.R")

temporal_cpsa_source <- Sys.getenv(
  "TEMPORALCPSA_SOURCE_DIR",
  Sys.getenv("AGETMP_TEMPORALCPSA_SOURCE_DIR", "")
)
if (nzchar(temporal_cpsa_source) && requireNamespace("pkgload", quietly = TRUE)) {
  pkgload::load_all(temporal_cpsa_source, quiet = TRUE)
} else if (requireNamespace("pkgload", quietly = TRUE) && dir.exists(file.path(repo_root, "temporalCPSA"))) {
  pkgload::load_all(file.path(repo_root, "temporalCPSA"), quiet = TRUE)
} else if (requireNamespace("temporalCPSA", quietly = TRUE)) {
  library(temporalCPSA)
} else {
  stop("Install temporalCPSA before running Figure 1F age-segmentation support.", call. = FALSE)
}

required_functions <- c(
  "ageTMP_segment_diagnostic_matrix",
  "ageTMP_plot_segment_diagnostic",
  "ageTMP_plot_segment_depth"
)
missing_functions <- required_functions[
  !vapply(required_functions, exists, logical(1), where = asNamespace("temporalCPSA"), inherits = FALSE)
]
if (length(missing_functions) > 0) {
  stop(
    "Installed temporalCPSA is missing required age-segmentation functions: ",
    paste(missing_functions, collapse = ", "),
    ". Please update temporalCPSA.",
    call. = FALSE
  )
}

out_dir <- Sys.getenv(
  "AGETMP_OUTPUT_DIR",
  file.path(script_dir, "output", "figure1f_source_derived_legacy_samples")
)
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

tmp_matrix_file <- Sys.getenv(
  "AGETMP_SOURCE_TMP_MATRIX",
  file.path(out_dir, "figure1f_ad_tmp_combined_tmp.tsv")
)
sample_annotation_file <- Sys.getenv(
  "AGETMP_SOURCE_SAMPLE_ANNOTATION",
  file.path(out_dir, "figure1f_ad_tmp_heatmap_source_derived_sample_annotations.tsv")
)
sample_metadata_file <- file.path(out_dir, "figure1f_ad_tmp_sample_metadata.tsv")

if (!file.exists(tmp_matrix_file)) {
  stop(
    "Source-derived Figure 1F AD-TMP matrix was not found at:\n",
    tmp_matrix_file,
    "\nRun `Rscript Figure1F_AD_TMP_heatmap_source_derived.R` first.",
    call. = FALSE
  )
}
if (!file.exists(sample_annotation_file) && !file.exists(sample_metadata_file)) {
  stop(
    "No source-derived Figure 1F sample annotation file was found. Run ",
    "`Rscript Figure1F_AD_TMP_heatmap_source_derived.R` first.",
    call. = FALSE
  )
}

message("Loading source-derived Figure 1F AD-TMP matrix...")
tmp_df <- utils::read.delim(tmp_matrix_file, check.names = FALSE)
feature_col <- tmp_df[[1]]
tmp_matrix <- as.matrix(tmp_df[, -1, drop = FALSE])
rownames(tmp_matrix) <- feature_col
storage.mode(tmp_matrix) <- "double"
colnames(tmp_matrix) <- temporalCPSA::ageTMP_normalize_sample_ids(colnames(tmp_matrix))

sample_df <- if (file.exists(sample_annotation_file)) {
  utils::read.delim(sample_annotation_file, check.names = FALSE)
} else {
  utils::read.delim(sample_metadata_file, check.names = FALSE)
}
sample_df$id <- temporalCPSA::ageTMP_normalize_sample_ids(sample_df$id)
sample_df$age <- suppressWarnings(as.numeric(sample_df$age))
sample_age <- sample_df$age
names(sample_age) <- sample_df$id

common_ids <- intersect(colnames(tmp_matrix), sample_df$id)
if (length(common_ids) < 20) {
  stop("Too few source-derived Figure 1F samples with age annotation.", call. = FALSE)
}
tmp_matrix <- tmp_matrix[, common_ids, drop = FALSE]
sample_age <- sample_age[common_ids]

k_values <- seq.int(
  as.integer(Sys.getenv("AGETMP_SEGMENT_MIN_K", "2")),
  as.integer(Sys.getenv("AGETMP_SEGMENT_MAX_K", "8"))
)
min_n <- as.integer(Sys.getenv("AGETMP_SEGMENT_MIN_N", "10"))

message("Fitting contiguous AD-TMP age segmentations for k = ", paste(k_values, collapse = ", "), "...")
diagnostic <- temporalCPSA::ageTMP_segment_diagnostic_matrix(
  tmp_matrix = tmp_matrix,
  sample_age = sample_age,
  k_values = k_values,
  min_n = min_n,
  scale_rows = FALSE
)
if (is.null(diagnostic$summary) || !"mean_silhouette" %in% names(diagnostic$summary)) {
  stop(
    "The installed temporalCPSA package does not include the updated ",
    "age-segmentation summary output. Please update temporalCPSA before ",
    "running this support script.",
    call. = FALSE
  )
}

summary_df <- diagnostic$summary
summary_df$cutpoints <- vapply(diagnostic$fits, function(fit) {
  paste(round(fit$cutpoints, 3), collapse = ";")
}, character(1))
summary_df$selected_by_max_mean_silhouette <- summary_df$k == summary_df$k[which.max(summary_df$mean_silhouette)]
utils::write.table(
  summary_df,
  file = file.path(out_dir, "figure1f_source_age_segmentation_summary.tsv"),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

ordered_samples <- diagnostic$ordered_samples
utils::write.table(
  ordered_samples,
  file = file.path(out_dir, "figure1f_source_age_segmentation_ordered_samples.tsv"),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

png_file <- file.path(out_dir, "figure1f_source_age_segmentation_diagnostic.png")
pdf_file <- file.path(out_dir, "figure1f_source_age_segmentation_diagnostic.pdf")
depth_png_file <- file.path(out_dir, "figure1f_source_age_segmentation_depth.png")
depth_pdf_file <- file.path(out_dir, "figure1f_source_age_segmentation_depth.pdf")

plot_diagnostic <- function() {
  temporalCPSA::ageTMP_plot_segment_diagnostic(
    diagnostic,
    selected_k = NULL,
    main = "Figure 1F source-derived AD-TMP age-segmentation support"
  )
}

grDevices::png(png_file, width = 1800, height = 950, res = 180)
plot_diagnostic()
grDevices::dev.off()

grDevices::pdf(pdf_file, width = 10, height = 5.5)
plot_diagnostic()
grDevices::dev.off()

plot_depth <- function() {
  temporalCPSA::ageTMP_plot_segment_depth(
    diagnostic,
    main = "Data-Driven Age-Segmentation Depth from AD-TMP Structure"
  )
}

grDevices::png(depth_png_file, width = 1600, height = 980, res = 170)
plot_depth()
grDevices::dev.off()

grDevices::pdf(depth_pdf_file, width = 10.5, height = 6.3)
plot_depth()
grDevices::dev.off()

cat("Figure 1F source-derived age-segmentation support written:\n")
cat(png_file, "\n")
cat(pdf_file, "\n")
cat(depth_png_file, "\n")
cat(depth_pdf_file, "\n")
cat(file.path(out_dir, "figure1f_source_age_segmentation_summary.tsv"), "\n")
