#!/usr/bin/env Rscript

# ============================================================
# Figure 4 / Figure S4 | Combined Frozen Sex-Specific Score Models
# File: Figure4_combined_frozen_score_models.R
#
# NOTE:
#   This script must be run AFTER Figure4_sex_specific_cox_models.R,
#   because it requires:
#
#     - Figure4_analysis_ready_data.rds
#
# Description:
#   Loads analysis-ready cDiscovery and validation data generated by the
#   sex-specific Cox model script and applies frozen male- and female-derived
#   prognostic score coefficients.
#
#   For each cohort, the script:
#     - computes male-derived and female-derived prognostic scores
#     - fits a combined Cox model with both continuous scores
#     - fits a combined Cox model with median-dichotomized scores
#     - outputs multivariable HR tables and HR plots
#     - outputs adjusted survival plots for each score
#
# Outputs:
#   Written to the current figure folder.
#
# Author: Nicole Tignor
# Affiliation: Icahn School of Medicine at Mount Sinai
# ============================================================

suppressPackageStartupMessages({
  library(survival)
  library(survminer)
  library(ggplot2)
  library(dplyr)
  library(cowplot)
  library(scales)
})

set.seed(123)

# ------------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------------

resolve_script_dir <- function(script_name) {
  for (frame in rev(sys.frames())) {
    ofile <- frame$ofile
    if (!is.null(ofile) && basename(ofile) == script_name && file.exists(ofile)) {
      return(dirname(normalizePath(ofile, mustWork = TRUE)))
    }
  }
  script_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(script_arg) > 0) {
    return(dirname(normalizePath(sub("^--file=", "", script_arg[[1]]), mustWork = TRUE)))
  }
  if (file.exists(file.path(getwd(), script_name))) {
    return(normalizePath(getwd(), mustWork = TRUE))
  }
  stop("Cannot determine script directory for `", script_name, "`. Run from the script folder or with Rscript.", call. = FALSE)
}
script_dir <- resolve_script_dir("Figure4_combined_frozen_score_models.R")
output_dir <- file.path(script_dir, "output")
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

analysis_ready_file <- file.path(
  output_dir,
  "Figure4_analysis_ready_data.rds"
)

sex_colors <- c(
  Male = "#0707CF",
  Female = "#CC0303",
  Both = "black"
)

text_size <- 13

# ------------------------------------------------------------------------------
# Helper functions
# ------------------------------------------------------------------------------

save_pdf <- function(plot_object, filename, width, height) {
  pdf(file.path(output_dir, filename), width = width, height = height)
  print(plot_object)
  dev.off()
}

make_score <- function(data, coefficients, score_name) {
  score_genes <- intersect(rownames(coefficients), colnames(data))
  
  if (length(score_genes) == 0) {
    stop("No overlapping genes found for ", score_name)
  }
  
  weights <- as.numeric(coefficients[score_genes, 1])
  names(weights) <- score_genes
  
  as.numeric(
    scale(as.matrix(data[, score_genes, drop = FALSE]) %*% weights * -1)
  )
}

make_median_group <- function(x) {
  cut(
    x,
    breaks = c(
      min(x, na.rm = TRUE),
      median(x, na.rm = TRUE),
      max(x, na.rm = TRUE)
    ),
    include.lowest = TRUE,
    labels = c("Low", "High")
  )
}

make_adjustment_data <- function(adjustment_covariates, n_rows) {
  data.frame(
    matrix(
      0,
      nrow = n_rows,
      ncol = length(adjustment_covariates),
      dimnames = list(NULL, adjustment_covariates)
    )
  )
}

add_validation_protein_to_clinical <- function(validation_clinical,
                                               validation_protein,
                                               score_genes) {
  
  validation_clinical <- as.data.frame(validation_clinical)
  
  if (!"SurvObj" %in% colnames(validation_clinical)) {
    validation_clinical$SurvObj <- survival::Surv(
      validation_clinical$survival_days,
      validation_clinical$os_status
    )
  }
  
  validation_ids <- intersect(
    validation_clinical$id,
    colnames(validation_protein)
  )
  
  validation_clinical <- validation_clinical[
    validation_clinical$id %in% validation_ids,
    ,
    drop = FALSE
  ]
  
  available_genes <- intersect(score_genes, rownames(validation_protein))
  
  if (length(available_genes) == 0) {
    stop("No frozen score genes found in validation protein matrix.")
  }
  
  missing_genes <- setdiff(score_genes, available_genes)
  
  if (length(missing_genes) > 0) {
    message(
      "Frozen score genes missing from validation protein matrix: ",
      paste(missing_genes, collapse = ", ")
    )
  }
  
  protein_sub <- validation_protein[
    available_genes,
    validation_clinical$id,
    drop = FALSE
  ]
  
  protein_sub <- t(scale(t(as.matrix(protein_sub))))
  protein_sub <- t(protein_sub)
  
  data.frame(validation_clinical, protein_sub)
}

# ------------------------------------------------------------------------------
# Load analysis-ready data
# ------------------------------------------------------------------------------

if (!file.exists(analysis_ready_file)) {
  stop(
    "Missing analysis-ready data file: ",
    analysis_ready_file,
    "\nRun Figure4_sex_specific_cox_models.R first."
  )
}

analysis_ready_data <- readRDS(analysis_ready_file)

cdiscovery_data <- analysis_ready_data$cDiscovery$data

validation_clinical <- if ("validation_data" %in% names(analysis_ready_data$validation)) {
  analysis_ready_data$validation$validation_data
} else {
  analysis_ready_data$validation$clinical
}

validation_protein <- analysis_ready_data$validation$protein

male_coefficients <- analysis_ready_data$coefficients$male_coefficients
female_coefficients <- analysis_ready_data$coefficients$female_coefficients

score_genes <- unique(c(
  rownames(male_coefficients),
  rownames(female_coefficients)
))

validation_data <- add_validation_protein_to_clinical(
  validation_clinical = validation_clinical,
  validation_protein = validation_protein,
  score_genes = score_genes
)

# ------------------------------------------------------------------------------
# Main combined-score analysis function
# ------------------------------------------------------------------------------

run_combined_score_model <- function(data, data_type) {
  
  message("Running combined frozen score model for: ", data_type)
  
  data <- as.data.frame(data)
  
  if (!"SurvObj" %in% colnames(data)) {
    stop("SurvObj not found in ", data_type, " data.")
  }
  
  data$prog.combined.male <- make_score(
    data,
    male_coefficients,
    "prog.combined.male"
  )
  
  data$prog.combined.female <- make_score(
    data,
    female_coefficients,
    "prog.combined.female"
  )
  
  data$male.cl <- make_median_group(data$prog.combined.male)
  data$female.cl <- make_median_group(data$prog.combined.female)
  
  data$male.cl <- factor(data$male.cl, levels = c("Low", "High"))
  data$female.cl <- factor(data$female.cl, levels = c("Low", "High"))
  
  adjustment_covariates <- c(
    "mut_H33A",
    "ado",
    "Midline",
    "Grade",
    "tumor",
    "Male"
  )
  
  adjustment_covariates <- intersect(
    adjustment_covariates,
    colnames(data)
  )
  
  model_covariates <- c(
    "prog.combined.male",
    "prog.combined.female",
    adjustment_covariates
  )
  
  data <- data[
    complete.cases(data[, model_covariates, drop = FALSE]),
    ,
    drop = FALSE
  ]
  
  continuous_formula <- as.formula(
    paste0(
      "SurvObj ~ prog.combined.male + prog.combined.female",
      if (length(adjustment_covariates) > 0) {
        paste0(" + ", paste(adjustment_covariates, collapse = " + "))
      } else {
        ""
      }
    )
  )
  
  binary_formula <- as.formula(
    paste0(
      "SurvObj ~ male.cl + female.cl",
      if (length(adjustment_covariates) > 0) {
        paste0(" + ", paste(adjustment_covariates, collapse = " + "))
      } else {
        ""
      }
    )
  )
  
  continuous_fit <- coxph(
    continuous_formula,
    control = coxph.control(iter.max = 2000),
    data = data
  )
  
  binary_fit <- coxph(
    binary_formula,
    control = coxph.control(iter.max = 2000),
    data = data
  )
  
  print(summary(continuous_fit))
  print(summary(binary_fit))
  
  save(
    data,
    continuous_fit,
    binary_fit,
    file = file.path(
      output_dir,
      paste0("combined_frozen_score_model_", data_type, ".RData")
    )
  )
  
  # --------------------------------------------------------------------------
  # Multivariable HR table and plot
  # --------------------------------------------------------------------------
  
  score_ci <- exp(confint(continuous_fit, level = 0.90))
  
  hr_table <- data.frame(
    Variable = rownames(score_ci),
    HR = exp(coef(continuous_fit)),
    CI_lower = score_ci[, 1],
    CI_upper = score_ci[, 2],
    stringsAsFactors = FALSE
  )
  
  hr_table <- hr_table %>%
    arrange(HR) %>%
    mutate(Variable = factor(Variable, levels = unique(Variable)))
  
  write.table(
    hr_table,
    file = file.path(
      output_dir,
      paste0("multivariate_hr_table_Both_", data_type, ".tsv")
    ),
    row.names = FALSE,
    sep = "\t",
    quote = FALSE
  )
  
  hr_plot <- ggplot(hr_table, aes(x = Variable, y = HR)) +
    geom_point(color = sex_colors[["Both"]], size = 3) +
    geom_errorbar(
      aes(ymin = CI_lower, ymax = CI_upper),
      width = 0.2,
      color = sex_colors[["Both"]]
    ) +
    geom_hline(yintercept = 1, linetype = "dashed", color = "red") +
    coord_flip() +
    scale_y_log10() +
    labs(
      x = "Variables",
      y = "Hazard Ratio"
    ) +
    facet_wrap(~paste0("HRs with 90% CIs (", data_type, ")")) +
    theme_bw()
  
  save_pdf(
    hr_plot,
    filename = paste0("multivariate_hr_plot_Both_", data_type, ".pdf"),
    width = 4.5,
    height = 3.5
  )
  
  # --------------------------------------------------------------------------
  # Adjusted survival plot: male-derived score
  # --------------------------------------------------------------------------
  
  newdata_male <- data.frame(
    male.cl = factor(c("High", "Low"), levels = c("Low", "High")),
    female.cl = factor(c("Low", "Low"), levels = c("Low", "High"))
  )
  
  rownames(newdata_male) <- newdata_male$male.cl
  
  newdata_male <- data.frame(
    newdata_male,
    make_adjustment_data(adjustment_covariates, nrow(newdata_male))
  )
  
  male_survfit <- survfit(binary_fit, newdata = newdata_male)
  
  pval_male <- formatC(
    summary(continuous_fit)$coef["prog.combined.male", 5],
    format = "e",
    digits = 1
  )
  
  male_score_plot <- ggsurvplot(
    male_survfit,
    data = newdata_male,
    title = paste0("Male-derived score - ", data_type),
    pval = paste0("Continuous score p = ", pval_male),
    conf.int = FALSE,
    linetype = "strata",
    legend.labs = c("High", "Low"),
    legend.title = "Male-derived score",
    xlab = "Time",
    ylab = "Survival Probability",
    risk.table = TRUE,
    palette = c(sex_colors[["Male"]], "gray40"),
    risk.table.fontsize = 5,
    ggtheme = theme_bw() +
      theme(
        plot.margin = margin(0, 0, 0, 0),
        plot.title = element_text(size = text_size),
        axis.title.x = element_text(size = text_size),
        axis.title.y = element_text(size = text_size),
        axis.text = element_text(size = text_size),
        legend.text = element_text(size = text_size),
        legend.title = element_text(size = text_size)
      ),
    tables.theme = theme_bw()
  )
  
  aligned_male <- cowplot::align_plots(
    male_score_plot$plot + theme(plot.margin = margin(r = 10)),
    male_score_plot$table + theme(plot.margin = margin(r = 10)),
    align = "v"
  )
  
  pdf(
    file.path(
      output_dir,
      paste0("prog_combined_male_score_", data_type, ".pdf")
    ),
    width = 6.2,
    height = 6.8
  )
  
  print(
    cowplot::plot_grid(
      aligned_male[[1]],
      aligned_male[[2]],
      ncol = 1,
      rel_heights = c(4, 1)
    )
  )
  
  dev.off()
  
  # --------------------------------------------------------------------------
  # Adjusted survival plot: female-derived score
  # --------------------------------------------------------------------------
  
  newdata_female <- data.frame(
    male.cl = factor(c("Low", "Low"), levels = c("Low", "High")),
    female.cl = factor(c("High", "Low"), levels = c("Low", "High"))
  )
  
  rownames(newdata_female) <- newdata_female$female.cl
  
  newdata_female <- data.frame(
    newdata_female,
    make_adjustment_data(adjustment_covariates, nrow(newdata_female))
  )
  
  female_survfit <- survfit(binary_fit, newdata = newdata_female)
  
  pval_female <- formatC(
    summary(continuous_fit)$coef["prog.combined.female", 5],
    format = "e",
    digits = 1
  )
  
  female_score_plot <- ggsurvplot(
    female_survfit,
    data = newdata_female,
    title = paste0("Female-derived score - ", data_type),
    pval = paste0("Continuous score p = ", pval_female),
    conf.int = FALSE,
    linetype = "strata",
    legend.labs = c("High", "Low"),
    legend.title = "Female-derived score",
    xlab = "Time",
    ylab = "Survival Probability",
    risk.table = TRUE,
    palette = c(sex_colors[["Female"]], "gray40"),
    risk.table.fontsize = 5,
    ggtheme = theme_bw() +
      theme(
        plot.margin = margin(0, 0, 0, 0),
        plot.title = element_text(size = text_size),
        axis.title.x = element_text(size = text_size),
        axis.title.y = element_text(size = text_size),
        axis.text = element_text(size = text_size),
        legend.text = element_text(size = text_size),
        legend.title = element_text(size = text_size)
      ),
    tables.theme = theme_bw()
  )
  
  aligned_female <- cowplot::align_plots(
    female_score_plot$plot + theme(plot.margin = margin(r = 10)),
    female_score_plot$table + theme(plot.margin = margin(r = 10)),
    align = "v"
  )
  
  pdf(
    file.path(
      output_dir,
      paste0("prog_combined_female_score_", data_type, ".pdf")
    ),
    width = 6.2,
    height = 6.8
  )
  
  print(
    cowplot::plot_grid(
      aligned_female[[1]],
      aligned_female[[2]],
      ncol = 1,
      rel_heights = c(4, 1)
    )
  )
  
  dev.off()
  
  invisible(
    list(
      data = data,
      continuous_fit = continuous_fit,
      binary_fit = binary_fit,
      hr_table = hr_table
    )
  )
}

# ------------------------------------------------------------------------------
# Run cDiscovery and validation analyses
# ------------------------------------------------------------------------------

combined_score_results <- list(
  cDiscovery = run_combined_score_model(
    cdiscovery_data,
    data_type = "cDiscovery"
  ),
  Validation = run_combined_score_model(
    validation_data,
    data_type = "Validation"
  )
)

save(
  combined_score_results,
  file = file.path(
    output_dir,
    "combined_frozen_score_results_cDiscovery_validation.RData"
  )
)

# ------------------------------------------------------------------------------
# Figure panel aliases
# ------------------------------------------------------------------------------

figure_aliases <- c(
  "multivariate_hr_plot_Both_cDiscovery.pdf" =
    "Figure4G_combined_score_HR_Both_cDiscovery.pdf",
  "prog_combined_male_score_cDiscovery.pdf" =
    "FigureS4F_combined_male_score_cDiscovery.pdf",
  "prog_combined_female_score_cDiscovery.pdf" =
    "FigureS4F_combined_female_score_cDiscovery.pdf",
  "multivariate_hr_plot_Both_Validation.pdf" =
    "Figure4H_combined_score_HR_Both_Validation.pdf",
  "prog_combined_male_score_Validation.pdf" =
    "FigureS4_combined_male_score_Validation.pdf", #not shown
  "prog_combined_female_score_Validation.pdf" =
    "FigureS4_combined_female_score_Validation.pdf"#not shown
)

for (source_file in names(figure_aliases)) {
  source_path <- file.path(output_dir, source_file)
  target_path <- file.path(output_dir, figure_aliases[[source_file]])
  
  if (file.exists(source_path)) {
    file.copy(source_path, target_path, overwrite = TRUE)
  } else {
    warning("Expected source file not found: ", source_path)
  }
}

message("Done. Combined frozen score outputs written to: ", output_dir)
